# Generated by Django 2.0.3 on 2018-03-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LernApp', '0003_project_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
