# Generated by Django 2.0.3 on 2018-03-18 09:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LernApp', '0004_auto_20180318_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=colorfield.fields.ColorField(default='red', max_length=18),
        ),
    ]
