# Generated by Django 2.0.3 on 2018-03-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LernApp', '0006_project_color2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='color2',
        ),
    ]
