# Generated by Django 2.0.3 on 2018-03-18 10:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LernApp', '0007_remove_project_color2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
